/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Product {
  id: string;
  name: string;
  price: string;
  image: string;
  category: 'fish' | 'shellfish' | 'crustacean' | 'specialty';
  freshness: string;
  description: string;
  isAvailable: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sankara fish',
    price: '₹300 (500g)',
    image: '/images/sankara_fish_fresh_1778996473319.png',
    category: 'fish',
    freshness: 'Caught 3h ago',
    description: 'Fresh Red Snapper (Sankara) known for its firm texture and sweet, mild flavor.',
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Vavval/ Black pomfret',
    price: '₹500 (500g)',
    image: '/images/black_pomfret_vavval_1778996701526.png',
    category: 'fish',
    freshness: 'Fresh Catch',
    description: 'Premium Black Pomfret (Vavval), highly prized for its delicious taste and rich texture.',
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Asal koduva/ sea bass',
    price: '₹500 (500g)',
    image: '/images/asal_koduva_sea_bass_1778996899255.png',
    category: 'fish',
    freshness: 'Daily Fresh',
    description: 'Premium Sea Bass (Asal koduva), known for its thick white flakes and delicate flavor.',
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Nethili/anchovy',
    price: '₹275 (500g)',
    image: '/images/nethili_anchovy_1778996915915.png',
    category: 'fish',
    freshness: 'Headless / Cleaned',
    description: 'Fresh Anchovies (Nethili), headless and ready for cooking. Great for traditional dishes.',
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Villai meen/emperor fish',
    price: '₹450 (500g)',
    image: '/images/emperor_fish_villai_1778996899260_1778997405730.png',
    category: 'fish',
    freshness: 'Daily Catch',
    description: 'Fresh Emperor fish (Villai meen), known for its sweet flavor and firm white meat.',
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Vanjiram/seer fish',
    price: '₹1300 (500g)',
    image: '/images/seer_fish_vanjiram_1778996899261_1778997425344.png',
    category: 'fish',
    freshness: 'Premium Quality',
    description: 'Steak-cut Seer fish (Vanjiram), the king of fishes, highly sought after for its rich taste.',
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Kannadi parai/ diamond travely',
    price: '₹515 (500g)',
    image: '/images/diamond_trevally_kannadi_parai_1778996899262_1778997444481.png',
    category: 'fish',
    freshness: 'Fresh Arrival',
    description: 'Fresh Diamond Trevally (Kannadi parai), prized for its delicate texture and mild oceanic taste.',
    isAvailable: true,
  },
  {
    id: '8',
    name: 'Kalavan/grouper fish',
    price: '₹500 (500g)',
    image: '/images/grouper_fish_kalavan_1778996899263_1778997462738.png',
    category: 'crustacean',
    freshness: 'Handpicked',
    description: 'Fresh Grouper fish (Kalavan), known for its lean, white meat and mild flavor profile.',
    isAvailable: true,
  },
  {
    id: '9',
    name: 'Aila/indian mackrel',
    price: '₹550 (500g)',
    image: '/images/indian_mackerel_aila_1778996899264_1778997478961.png',
    category: 'fish',
    freshness: 'Coastal Catch',
    description: 'Fresh Indian Mackerel (Aila), rich in Omega-3 and perfect for frying or curries.',
    isAvailable: true,
  },
  {
    id: '10',
    name: 'Parla/mahi mahi fish',
    price: '₹500 (500g)',
    image: '/images/mahi_mahi_parla_1778998266083.png',
    category: 'fish',
    freshness: 'Fresh Catch',
    description: 'Fresh Mahi Mahi (Parla), also known as dolphin fish, with a firm texture and mild, sweet flavor.',
    isAvailable: true,
  },
  {
    id: '11',
    name: 'Matthi / sardine fish',
    price: '₹250 (500g)',
    image: '/images/sardine_matthi_1778998281456.png',
    category: 'fish',
    freshness: 'Daily Coastal Catch',
    description: 'Fresh Indian Sardines (Matthi), rich in Omega-3 and perfect for traditional curries.',
    isAvailable: true,
  },
  {
    id: '12',
    name: 'Baby shark',
    price: '₹250 (500g)',
    image: '/images/baby_shark_pile_1778998296514.png',
    category: 'specialty',
    freshness: 'Premium Quality',
    description: 'Fresh Baby Shark, a traditional delicacy known for its tender meat and unique flavor.',
    isAvailable: true,
  },
  {
    id: '13',
    name: 'Pal sura/ milk shark',
    price: '₹550 (500g)',
    image: '/images/milk_shark_pal_sura_1778998313921.png',
    category: 'fish',
    freshness: 'Fine Quality',
    description: 'Premium Milk Shark (Pal sura), highly recommended for its nutritional value and soft meat.',
    isAvailable: true,
  },
  {
    id: '14',
    name: 'Kadal viral/cobia fish',
    price: '₹410 (500g)',
    image: '/images/cobia_kadal_viral_1778998329313.png',
    category: 'shellfish',
    freshness: 'Large Sized',
    description: 'Fresh Cobia (Kadal viral), with a firm texture and buttery flavor, suitable for grilling.',
    isAvailable: true,
  },
  {
    id: '15',
    name: 'White snapper / korrukkai fish',
    price: '₹400 (500g)',
    image: '/images/white_snapper_korrukkai_1778998347552.png',
    category: 'fish',
    freshness: 'Market Fresh',
    description: 'Fresh White Snapper (Korrukkai), prized for its delicate white flakes and light flavor.',
    isAvailable: true,
  },
  {
    id: '16',
    name: 'Red snapper fish',
    price: '₹400 (500g)',
    image: '/images/red_snapper_market_1778998365359.png',
    category: 'fish',
    freshness: 'Vibrant Catch',
    description: 'Fresh Red Snapper, a premium fish with a sweet and nutty flavor, perfect for roasting.',
    isAvailable: true,
  },
  {
    id: '17',
    name: 'Karapodi/silver belly fish',
    price: '₹300 (500g)',
    image: '/images/silver_belly_karapodi_1778998382963.png',
    category: 'fish',
    freshness: 'Small & Tasty',
    description: 'Fresh Silver Belly (Karapodi), small fish perfect for crispy frying or light curries.',
    isAvailable: true,
  },
  {
    id: '18',
    name: 'Nakkumeen/halibut fish',
    price: '₹400 (500g)',
    image: '/images/halibut_background_change_1778998402410.png',
    category: 'fish',
    freshness: 'Top Grade',
    description: 'Fresh Halibut (Nakkumeen), an excellent choice for its mild flavor and firm, meaty texture.',
    isAvailable: true,
  },
  {
    id: '19',
    name: 'Sheela/barracuda',
    price: '₹400 (500g)',
    image: '/images/barracuda_sheela_1778998421885.png',
    category: 'fish',
    freshness: 'Sleek Catch',
    description: 'Fresh Barracuda (Sheela), known for its bold flavor and firm, white meat.',
    isAvailable: true,
  },
  {
    id: '20',
    name: 'Soorai/Tuna fish',
    price: '₹500 (500g)',
    image: '/images/tuna_soorai_fresh_1778999191151.png',
    category: 'fish',
    freshness: 'Deep Sea Catch',
    description: 'Fresh Tuna (Soorai), known for its meaty texture and rich flavor, perfect for steaks or curries.',
    isAvailable: true,
  },
  {
    id: '21',
    name: 'squid',
    price: '₹350 (500g)',
    image: '/images/squid_fresh_shellfish_1778999213288.png',
    category: 'shellfish',
    freshness: 'Fresh Arrival',
    description: 'Fresh Squid, tender and flavorful, ideal for calamari rings or traditional seafood masalas.',
    isAvailable: true,
  },
  {
    id: '22',
    name: 'Manja parai/yellow travelly',
    price: '₹450 (500g)',
    image: '/images/yellow_trevally_manja_parai_1778999232774.png',
    category: 'fish',
    freshness: 'Premium Selection',
    description: 'Fresh Yellow Trevally (Manja Parai), distinctive for its yellow markings and firm, tasty flesh.',
    isAvailable: true,
  },
  {
    id: '23',
    name: 'Parai / travlly fish',
    price: '₹450 (500g)',
    image: '/images/trevally_parai_white_bg_1778999248794.png',
    category: 'fish',
    freshness: 'Market Fresh',
    description: 'Fresh Trevally (Parai), a popular choice for its versatile cooking options and moderate flavor.',
    isAvailable: true,
  },
  {
    id: '24',
    name: 'Jilebi/ tilapia',
    price: '₹175 (500g)',
    image: '/images/tilapia_jilebi_fresh_1778999264187.png',
    category: 'fish',
    freshness: 'Freshwater Fresh',
    description: 'Fresh Tilapia (Jilebi), affordable and mild-tasting, great for quick family meals.',
    isAvailable: true,
  },
  {
    id: '25',
    name: 'Cutla fish',
    price: '₹160 (500g)',
    image: '/images/cutla_fish_fresh_1778999284296.png',
    category: 'shellfish',
    freshness: 'Daily Harvest',
    description: 'Fresh Cutla fish, a major carp with a sweet flavor and tender texture.',
    isAvailable: true,
  },
  {
    id: '26',
    name: 'Yeri vavval / roopchand',
    price: '₹175 (500g)',
    image: '/images/roopchand_yeri_vavval_1778999302294.png',
    category: 'fish',
    freshness: 'Quality Catch',
    description: 'Fresh Roopchand (Yeri Vavval), known for its single bone and soft, delicious meat.',
    isAvailable: true,
  },
  {
    id: '27',
    name: 'Basa fish/ pangasius',
    price: '₹200 (500g)',
    image: '/images/basa_fish_pangasius_1778999321360.png',
    category: 'fish',
    freshness: 'Sleek Quality',
    description: 'Fresh Basa (Pangasius), with a light, firm texture and mild flavor, excellent for fillets.',
    isAvailable: true,
  },
  {
    id: '28',
    name: 'Karimeen/pearl spot',
    price: '₹350 (500g)',
    image: '/images/pearl_spot_karimeen_fresh_1778999351513.png',
    category: 'fish',
    freshness: 'Native Catch',
    description: 'Fresh Pearl Spot (Karimeen), a backwater delicacy with a highly prized, unique taste.',
    isAvailable: true,
  },
  {
    id: '29',
    name: 'Fresh water prawns',
    price: '₹350 (500g)',
    image: '/images/fresh_water_prawns_60_80_1778999369644.png',
    category: 'crustacean',
    freshness: '60-80 counts',
    description: 'Fresh Water Prawns, juicy and tender, perfect for stir-fries and curries.',
    isAvailable: true,
  },
  {
    id: '30',
    name: 'sea white prawns',
    price: '₹300 (500g)',
    image: '/images/sea_white_prawns_60_80_1778999386344.png',
    category: 'crustacean',
    freshness: '60-80 counts',
    description: 'Fresh Sea White Prawns, with a sweet oceanic flavor and crisp texture.',
    isAvailable: true,
  },
  {
    id: '31',
    name: 'Crab three spot',
    price: '₹300 (500g)',
    image: '/images/crab_three_spot_1779000000000_1779000088563.png',
    category: 'crustacean',
    freshness: 'Fresh Catch',
    description: 'Fresh Three-spot Crab, known for its distinctive markings and sweet, tender meat.',
    isAvailable: true,
  },
  {
    id: '32',
    name: 'Blue crab big',
    price: '₹550 (500g)',
    image: '/images/blue_crab_fresh_1779000000001_1779000104081.png',
    category: 'crustacean',
    freshness: 'Premium Size',
    description: 'Large Blue Crabs, highly desired for their rich, succulent meat and beautiful appearance.',
    isAvailable: true,
  },
  {
    id: '33',
    name: 'Tiger prawns',
    price: '₹600 (500g)',
    image: '/images/tiger_prawns_30_counts_1779000000002_1779000122707.png',
    category: 'crustacean',
    freshness: '30 counts',
    description: 'Jumbo Tiger Prawns, premium quality with a firm texture and sweet, robust flavor.',
    isAvailable: true,
  },
  {
    id: '34',
    name: 'Lobsters',
    price: '₹2000 (1kg)',
    image: '/images/lobsters_market_fresh_1779000000003_1779000142560.png',
    category: 'crustacean',
    freshness: 'Ocean Fresh',
    description: 'Whole Fresh Lobsters, the ultimate seafood luxury with unparalleled sweet and tender meat.',
    isAvailable: true,
  },
  {
    id: '35',
    name: 'Mud crab/ green live crab',
    price: '₹2000 (1kg)',
    image: '/images/mud_crab_basket_1779000000004_1779000157807.png',
    category: 'crustacean',
    freshness: 'Live / Fresh',
    description: 'Premium Mud Crabs (Green live crab), known for their massive claws and abundant sweet meat.',
    isAvailable: true,
  },
  {
    id: '36',
    name: 'Vellai vavval/chinese pomfet',
    price: '₹800 (500g)',
    image: '/images/chinese_pomfret_vellai_1779000000005_1779000174302.png',
    category: 'fish',
    freshness: 'Exquisite Catch',
    description: 'Premium Chinese Pomfret (Vellai vavval), the most prized variety of pomfret with a delicate flavor.',
    isAvailable: true,
  },
  {
    id: '37',
    name: 'Thengai parai/ travelky fish',
    price: '₹450 (500g)',
    image: '/images/thengai_parai_trevally_1779000000006_1779000191791.png',
    category: 'fish',
    freshness: 'Sturdy Catch',
    description: 'Fresh Trevally (Thengai parai), a substantial fish with a great texture for hearty seafood dishes.',
    isAvailable: true,
  }
];
